import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-[#000319] relative"}>
        <div className="bg-grid-white/[0.05] shadow-[inset_0_0_25rem_15rem_rgba(0,0,0,0.5)]">
          {children}
        </div>
      </body>
    </html>
  );
}
